[project]
name = "flood-forecasting"
version = "0.1.0"
description = ""
requires-python = ">=3.11"
dependencies = [
    "polars>=1.0.0",
    "torch>=2.0.0",
    "scikit-learn>=1.5.0",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "pytest",
]
