# CI smoke test config: 10 sites, 3 days of data for fast validation
ops:
  usgs_site_metadata:
    config:
      sample_mode: true
      max_sites: 10
  usgs_streamflow_15min:
    config:
      sample_mode: true
      max_sites: 10
      days_back: 3
  usgs_streamflow_daily:
    config:
      sample_mode: true
      max_sites: 10
      days_back: 3
  weather_forcing_raw:
    config:
      sample_mode: true
      max_sites: 10
      days_back: 3
